### ISSUE TITLE
Add Unique Constraints to Schema.sql

### ISSUE THREAD

**Issue by AlexOBarnes** [AlexOBarnes/LMNH-Project#22]
As a botanist, I would like to ensure that the data we are storing is as rigorous as possible so that when I am analysing the data there are no errors occurring due to duplicated rows so that I can trust the analysis I am conducting.

- Add constraints to schema.sql
- Use UNIQUE generated always as ID to ensure rigorous data storage

**Comment by paulauus** [comment]
We have added unique constraints to the schema together.
