### ISSUE TITLE
Provision RDS using Terraform

### ISSUE THREAD

**Issue by indiah444** [AlexOBarnes/LMNH-Project#24]
As a stakeholder at LMNH, I want to hold plant data for the last 24 hours in a place that is cost-effective and easily accessible, so that I can help to keep costs low, but also access the data to see trends and key data.

- Use Terraform to provision the RDS
- Create a maintainable and reproducible script 
- Use terraform.tfvars files to properly store secret values

**Comment by paulauus** [comment]
We did not need to provision the RDS database ourselves, because the credentials for one were sent to us on Slack. The RDS database already exists.
